apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: diegoperea/api-reviews
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_ENV
              value: development
